packages:
  - packages/*
catalog:
  '@tanstack/react-query': ^4.36.1
  '@trpc/client': ^10.45.2
  '@trpc/react-query': ^10.45.2
  '@trpc/server': ^10.45.2
  '@types/react': ^18.3.8
  '@types/react-dom': ^18.3.0
  '@vitejs/plugin-react': ^4.3.1
  react: ^18.3.1
  react-dom: ^18.3.1
  vite: ^5.4.6
  zod: ^3.23.8
